"""Typed shared state passed between graph nodes (PRD S6.3, S6.4).

The defining constraint here is T2 (filesystem as working memory): state holds
pointers and small scalars, never content. The 4 KB per-field rule is enforced
at construction rather than documented and hoped for, because the failure it
prevents — context-window exhaustion partway through a long run — surfaces far
from the line of code that caused it.
"""

from __future__ import annotations

import hashlib
import json
import time
from pathlib import Path
from typing import Any, Self

from pydantic import BaseModel, ConfigDict, Field, model_validator

from xeno.core.types import BreakerCode, Breakpoint, NodeRole, Tier, Verdict

#: PRD S6.3 HARD RULE: no AgentState field may exceed this serialized size.
#: Anything larger is a Handle.
MAX_FIELD_BYTES = 4096

#: Handle summaries are one-liners. Capped so a list of handles stays inside
#: the field budget above, and so a file cannot smuggle a paragraph of
#: instructions through its own summary line (PRD S11.4).
MAX_SUMMARY_CHARS = 200


class Handle(BaseModel):
    """A reference to a filesystem artifact under .xeno/ (PRD S17).

    Passed in state instead of content. The `summary` is generated by the
    HARNESS, never copied from the file's own text — otherwise a repository
    file could inject instructions via the line that describes it (PRD S11.4).
    """

    model_config = ConfigDict(frozen=True)

    path: Path
    sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    summary: str = Field(max_length=MAX_SUMMARY_CHARS)
    bytes: int = Field(ge=0)

    @classmethod
    def for_file(cls, path: Path, summary: str) -> Self:
        """Build a handle by hashing a file that already exists on disk."""
        data = path.read_bytes()
        return cls(
            path=path,
            sha256=hashlib.sha256(data).hexdigest(),
            summary=_truncate(summary, MAX_SUMMARY_CHARS),
            bytes=len(data),
        )

    def read_text(self) -> str:
        """Dereference the handle. Nodes call this on demand, never eagerly."""
        return self.path.read_text()

    def verify(self) -> bool:
        """True if the on-disk artifact still matches the recorded digest."""
        if not self.path.exists():
            return False
        return hashlib.sha256(self.path.read_bytes()).hexdigest() == self.sha256


class BreakpointStats(BaseModel):
    """Cached vs. fresh input tokens at one prompt breakpoint."""

    hit_tokens: int = 0
    miss_tokens: int = 0
    write_tokens: int = 0  # tokens billed at the cache-WRITE multiplier

    @property
    def eligible_tokens(self) -> int:
        return self.hit_tokens + self.miss_tokens + self.write_tokens

    @property
    def hit_rate(self) -> float | None:
        """Fraction served from cache. None when nothing eligible was sent."""
        total = self.eligible_tokens
        return self.hit_tokens / total if total else None


class CacheStats(BaseModel):
    """Per-node cache accounting, keyed by breakpoint (PRD S6.3, S9.6.4).

    This is the instrument for M1.4. A ledger that cannot distinguish cached
    from fresh tokens cannot report M1.1-M1.4 honestly (PRD S9.6.4).
    """

    by_breakpoint: dict[Breakpoint, BreakpointStats] = Field(default_factory=dict)

    def record(
        self,
        breakpoint: Breakpoint,
        *,
        hit: int = 0,
        miss: int = 0,
        write: int = 0,
    ) -> None:
        stats = self.by_breakpoint.setdefault(breakpoint, BreakpointStats())
        stats.hit_tokens += hit
        stats.miss_tokens += miss
        stats.write_tokens += write

    @property
    def hit_rate(self) -> float | None:
        """M1.4: fraction of eligible input tokens served from cache."""
        hits = sum(s.hit_tokens for s in self.by_breakpoint.values())
        total = sum(s.eligible_tokens for s in self.by_breakpoint.values())
        return hits / total if total else None


class EvalReport(BaseModel):
    """Talos's structured output. Always small; the log itself is a handle."""

    parse_ok: bool = False
    lint_errors: int = 0
    type_errors: int = 0
    tests_run: int = 0
    tests_failed: int = 0
    coverage_delta: float | None = None
    first_failure: str = Field(default="", max_length=500)
    full_log_handle: Handle | None = None

    #: Distinguishes a code defect from a sandbox/adapter fault. Infrastructure
    #: failures consume one L0 retry then route straight to ESCALATE — they are
    #: never fed to Chiron, because there is no code defect to patch (PRD S10).
    infrastructure_failure: bool = False

    #: Set when a patch touched a test file. Cerberus treats such a diff as
    #: presumptively invalid (PRD S10, Chiron hard rule).
    touched_test_files: list[str] = Field(default_factory=list)

    @property
    def passed(self) -> bool:
        return (
            self.parse_ok
            and not self.infrastructure_failure
            and self.lint_errors == 0
            and self.type_errors == 0
            and self.tests_failed == 0
        )


class CommitRef(BaseModel):
    """A checkpoint: a commit on the isolated branch with all gates green."""

    model_config = ConfigDict(frozen=True)

    sha: str
    task_index: int
    message: str = Field(max_length=200)
    created_at: float


class BreakerTrip(BaseModel):
    """A fired circuit breaker. Forces an immediate jump to L5 / Cerberus."""

    model_config = ConfigDict(frozen=True)

    code: BreakerCode
    detail: str = Field(max_length=500)
    fired_at: float = Field(default_factory=time.time)


class AgentState(BaseModel):
    """The typed state passed between nodes (PRD S6.3).

    Every field is a pointer or a small scalar. Construction and mutation both
    run the 4 KB check.
    """

    model_config = ConfigDict(validate_assignment=True)

    run_id: str
    goal: str

    plan: Handle | None = None
    task_cursor: int = 0
    task_count: int = 0
    context_handles: list[Handle] = Field(default_factory=list)
    diff_handle: Handle | None = None
    #: Rolling window of recent diffs' content hashes (PRD CB-5): a repeat
    #: means the working diff returned to a byte-identical prior state, i.e.
    #: the agent is oscillating between two wrong answers. A window, not the
    #: full run history — oscillation is inherently a short-cycle pattern,
    #: and an unbounded list would eventually threaten the 4 KB field limit
    #: on a long run (PRD S6.3).
    diff_history: list[str] = Field(default_factory=list)
    eval_report: EvalReport | None = None

    failure_signature: str | None = None
    #: See the CB-4 counting rule (PRD S7.3): the first failure of a plan task
    #: is the baseline and is NOT counted. This increments only when a
    #: signature survives a model-authored intervention unchanged.
    signature_streak: int = 0

    #: 0-5, per plan task. Monotonic within a task; reset on task advance.
    ladder_rung: int = Field(default=0, ge=0, le=5)
    #: Attempts consumed at the current rung, against RUNG_BUDGETS.
    rung_attempts: int = 0

    #: Cerberus rejections this run. NOT a ladder rung; separate budget (S8.3).
    reject_count: int = 0

    iteration_count: int = 0
    iterations_this_task: int = 0

    tokens_spent: dict[Tier, int] = Field(default_factory=dict)
    #: Keyed by model actually billed, so upward fallback counts against M1.1
    #: (PRD S9.5). Do not derive this from declared node tier.
    tokens_by_model: dict[str, int] = Field(default_factory=dict)
    cache_stats: dict[str, CacheStats] = Field(default_factory=dict)
    usd_spent: float = 0.0

    wall_clock_start: float = Field(default_factory=time.time)
    checkpoints: list[CommitRef] = Field(default_factory=list)

    review_verdict: Verdict | None = None
    halt_reason: str | None = None
    breaker_trips: list[BreakerTrip] = Field(default_factory=list)

    #: Cerberus's full accumulated run diff (PRD S8.2), recomputed on every
    #: Cerberus invocation via `vcs.diff_since` — never `diff_handle`, which
    #: stays the LAST write's diff only (still needed by CB-5). Set on both
    #: the reviewed and the deterministic-escalate branches, so the CLI can
    #: always show "the current diff" once the graph terminates.
    review_diff_handle: Handle | None = None

    #: Cerberus's written prose, reused across all three verdicts: APPROVE's
    #: notes, REJECT_AND_RETURN's objections, or ESCALATE's report. `None`
    #: only when an ESCALATE was forced by Cerberus's own chain exhaustion
    #: (PRD S8.2 "Failure") — that absence IS the UNREVIEWED signal, so no
    #: separate boolean field is needed for it.
    cerberus_notes: Handle | None = None

    #: Cerberus's proposed conventional-commit message (APPROVE only).
    #: Inline, not a Handle: comfortably under the 4 KB field limit, and the
    #: squash step needs the raw string directly.
    commit_message: str | None = None

    #: Cerberus's E16/E17 routing choice on REJECT_AND_RETURN: `CODER`
    #: (Daedalus, implementation flaw) or `PLANNER` (Odysseus, plan flaw).
    #: Written once by the Cerberus node; the node that reads it (Daedalus or
    #: Odysseus) clears it back to `None` immediately after, so a later,
    #: unrelated call to that same node can never misread a stale value.
    reject_destination: NodeRole | None = None

    @model_validator(mode="after")
    def _enforce_field_size(self) -> Self:
        """PRD S6.3 hard rule: no field may exceed 4 KB serialized."""
        for name in type(self).model_fields:
            value = getattr(self, name)
            size = len(stable_json(value).encode())
            if size > MAX_FIELD_BYTES:
                raise ValueError(
                    f"AgentState.{name} is {size} bytes, over the {MAX_FIELD_BYTES}-byte "
                    f"limit (PRD S6.3). Write it to .xeno/workspace/ and pass a Handle."
                )
        return self

    @property
    def elapsed_seconds(self) -> float:
        return time.time() - self.wall_clock_start

    @property
    def halted(self) -> bool:
        return self.halt_reason is not None

    def cache_stats_for(self, node: str) -> CacheStats:
        return self.cache_stats.setdefault(node, CacheStats())


def _truncate(text: str, limit: int) -> str:
    collapsed = " ".join(text.split())
    if len(collapsed) <= limit:
        return collapsed
    return collapsed[: limit - 1] + "…"


def stable_json(value: Any) -> str:
    """Deterministic JSON for size checks and hashing."""

    def default(obj: Any) -> Any:
        if isinstance(obj, BaseModel):
            return obj.model_dump(mode="json")
        if isinstance(obj, Path):
            return str(obj)
        return str(obj)

    return json.dumps(value, sort_keys=True, default=default, separators=(",", ":"))
